### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by koushikpuppala** [casperiv0/ghostybot#108]
**Description**
Please provide as much info as you can.

![2020-11-19 (1)](https://user-images.githubusercontent.com/70138027/99633758-6fc24c00-2a65-11eb-9bc8-fc7ecad569fb.png)

**Comment by casperiv0** [comment]
Make sure you are on node v14

**Comment by koushikpuppala** [comment]
Yes mine is latest node v15. 2.0

**Comment by casperiv0** [comment]
Hmm, doesn’t look like it. Can you run `node -v` And show me the response

**Comment by koushikpuppala** [comment]
how to get the OpenWeatherMap key
![2020-11-19 (2)](https://user-images.githubusercontent.com/70138027/99643833-30026100-2a73-11eb-9e07-b05ca774afcc.png)

**Comment by koushikpuppala** [comment]
how to get the OpenWeatherMap key

**Comment by casperiv0** [comment]
> how to get the OpenWeatherMap key

https://openweathermap.org/api

**Comment by koushikpuppala** [comment]
how to change prefix

**Comment by new-step-apps** [comment]
You mean default prefix 
And you can change it by command 
!prefix (your new prefix)

**Comment by koushikpuppala** [comment]
For global

**Comment by koushikpuppala** [comment]
As like your bot !

**Comment by new-step-apps** [comment]
At path 
Src/events/message.js

**Comment by new-step-apps** [comment]
You can join ghostybot server to have fast Answers 🙂

**Comment by koushikpuppala** [comment]
link

**Comment by casperiv0** [comment]
You can join here: https://discord.gg/WaJ4BVjz

**Comment by koushikpuppala** [comment]
i have joined
