### ISSUE TITLE
What is 'chalk'

### ISSUE THREAD

**Issue by JOK3R131** [casperiv0/ghostybot#112]
**Description**
Hi! I tried to create a bot similar to your ghostybot. When I try to run my bot, it displays something like this:

`Error: Cannot find module 'chalk' `

So I can't run the bot. I was looking for a chalk file in your [GitHub repository](https://github.com/Dev-CasperTheGhost/ghostybot) but found nothing. Can You help me?

**Comment by ghost** [comment]
Please read [Disclaimer if self-hosted](https://github.com/Dev-CasperTheGhost/ghostybot#disclaimer-if-self-hosted).

**Comment by casperiv0** [comment]
Like @Tegnio6882 said, we will not be providing support for people who self-host anymore.

**Comment by Assassin-1234** [comment]
@JOK3R131 chalk is a module that you dont have installed. to fix this, use `npm install chalk` in your console

**Comment by JOK3R131** [comment]
**Thank you for all your help :-)**
