### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by skillzl** [casperiv0/ghostybot#116]
**FetchError:** invalid json response body at http://localhost:3030/api/guilds reason: Unexpected token I in JSON at position 0

**Error screenshots:**
- https://cdn.charliewave.me/WindowsTerminal_847cKXv0Gm.png
- https://cdn.charliewave.me/UJMqvr4czE.png

**Comment by casperiv0** [comment]
Make sure to update your local bot, this looks like it's a few commits behind.

**Comment by skillzl** [comment]
yeah, it is an old version that i enchanted a little bit, yea ty im gonna try with this new version
