### ISSUE TITLE
I need to run bot to my Clash of Clans server how can I stop dashboard

### ISSUE THREAD

**Issue by koushikpuppala** [casperiv0/ghostybot#119]
**Description**
Please provide as much info as you can.
**Please tell me how to disable or remove dashboard**

**Comment by casperiv0** [comment]
Hi, I'll quickly add a feature so you can simple disable the dashboard.

**Comment by casperiv0** [comment]
Done, you can add `"enabled": false` to your config in the dashboard section (see config.example.json) for reference.
