### ISSUE TITLE
Help-me

### ISSUE THREAD

**Issue by ghost** [casperiv0/ghostybot#123]
Dashboard: Internal Server Error
Console: Error: secretOrPrivateKey must have a value
![image](https://user-images.githubusercontent.com/74716083/102017153-eb04de00-3d43-11eb-8417-466b2c017b4b.png)
![image](https://user-images.githubusercontent.com/74716083/102017175-0bcd3380-3d44-11eb-85c7-06d118dc558e.png)

**Comment by casperiv0** [comment]
Make sure `jwtSecret` has a value, this value can be anything random

**Comment by EnzoScripter** [comment]
when I click "open panel" and then authorize it returns again to the authorization page

**Comment by casperiv0** [comment]
There's no "open panel" anywhere? What do you mean with that?

**Comment by ghost** [comment]
when I click the dashboard button and authorize the application, it simply returns to the authorization page and the following error: Error: payload is required

**Comment by casperiv0** [comment]
This might be an issue related to that Discord is experiencing some issues at the moment, I suggest trying in a few hours, if it still doesn't work let me know.

**Comment by ghost** [comment]
ok thanks.
