### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by biswajitguha01** [casperiv0/ghostybot#124]
Can u please tell if I want dashboard true then I have to buy a domain ? Or website? 
& also one thing that reaction role command does not we work

**Comment by ghost** [comment]
There is no need to buy a domain if you're testing, the dashboard will run on `https://localhost:3030`. But if it's a public bot, you should buy one.

**Comment by biswajitguha01** [comment]
Thanks for help !

**Comment by biswajitguha01** [comment]
Reactions role commands does not work .. it doesn’t give any role when react .

**Comment by koushikpuppala** [comment]
**make sure the bot is higher than the role you want to assign**

**Comment by biswajitguha01** [comment]
Bot is already in higher role

**Comment by koushikpuppala** [comment]
But it is working for us

**Comment by casperiv0** [comment]
It's working for us. Make sure there are no errors, and make sure everything is setup right

**Comment by biswajitguha01** [comment]
Ok thanks for help ! Can you please add sharding in this project?? This is better to know how to add shards in a bot. By the way your project is very powerful.

**Comment by casperiv0** [comment]
You'll need to setup that yourself. You can check the guide on https://discordjs.guide

**Comment by biswajitguha01** [comment]
Thanks 🙏🏻. & one question in setwelcomemsg command custom emojis are supported or not ?

**Comment by casperiv0** [comment]
They should if the bot is in the same server of where the emojis come from.

**Comment by biswajitguha01** [comment]
Hello sir, can you add  anti link spam or anti spam command ? Like auto moderation.

**Comment by casperiv0** [comment]
I'll see. For now I will close this issue since it seems like your all good to go.
