### ISSUE TITLE
New Features Request

### ISSUE THREAD

**Issue by biswajitguha01** [casperiv0/ghostybot#127]
I just want to know can you add setup ticket command??

**Comment by casperiv0** [comment]
Most likely I won't add this feature anytime soon, feel free to make it yourself tho.

**Comment by tovade** [comment]
i mean i can do it

**Comment by tovade** [comment]
its mongoDB

**Comment by biswajitguha01** [comment]
Yes I can do it with quick db but don’t know how to do with mongo db

**Comment by tovade** [comment]
i dont contribute anymore since the config is getting bigger and takes longer to get keys for some apis

**Comment by casperiv0** [comment]
It's pretty much the same but just some functions are different

**Comment by tovade** [comment]
you can use the docs tho

**Comment by casperiv0** [comment]
Good news, I'll add this feature since I've got a another request for it. Not sure when I'll be done tho

**Comment by Cabotrez** [comment]
Add it 😋

**Comment by casperiv0** [comment]
Just added the feature, for now only admins are able to view the ticket channels but I'll be adding a section for ticket roles in the `guild settings` on the dashboard

**Comment by casperiv0** [comment]
All done :)
