### ISSUE TITLE
Discord-starboards breaking changes

### ISSUE THREAD

**Issue by SimonLeclere** [casperiv0/ghostybot#154]
Hey, I just pushed a new update on the discord-starboards develop branch. It fixes many bugs and introduces new features like the NSFW channel filter, custom emojis, ...

Unfortunately it may break your code.

Consider updating your code and let me know if you encounter any bugs. If all goes well, let me know and I'll merge the develop branch to the main branch.

Have a nice evening,

Simon.

PS: The delete and deleteStarboard methods have changed

**Comment by casperiv0** [comment]
Will check it out soon, Thanks for letting me know! For now I'll leave this issue open so I don't forget lol.

**Comment by casperiv0** [comment]
I will close this issue now, I'll open an issue on your repo if I encounter any bugs :)
