### ISSUE TITLE
The Newbie is Back!

### ISSUE THREAD

**Issue by DiabolicAngeL** [casperiv0/ghostybot#159]
**Description**
Hello again Casper, it's been a long time. I hope you're doing well.
I'm trying to setup your bot but of course I'm not doing it right and I need your help.
I managed to setup everything (I think)

I am just getting the following error.

```
MongooseError: Operation `bots.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/ghostybot/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:184:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

I am using https://cloud.mongodb.com

Thanks a lot!
Great job once again!

Can't wait to be back and try your new CAD too!

**Comment by casperiv0** [comment]
Make sure the login to the db is correct

**Comment by DiabolicAngeL** [comment]
Hello casper,

here is my link `mongodb+srv://dgbotghost:<password-here>@<cluster-name>.6x9t7.mongodb.net/discordbotdg?retryWrites=true`

I tried with `discordbotdg.discordbotdg` too. Maybe I'm doing something else wrong

![image](https://user-images.githubusercontent.com/68332732/104345725-568ac880-5507-11eb-8bac-27aed915f6cc.png)

**Comment by tovade** [comment]
try remove the ?retryWrites=true

**Comment by DiabolicAngeL** [comment]
> try remove the ?retryWrites=true

Thank you for the reply,
No, that didn't work

**Comment by casperiv0** [comment]
Make sure to user: `mongodb+srv://<user here>` is correct, you can check [in the database access](https://cloud.mongodb.com/v2/5e749804009db21dd6c90af1#security/database/users) and make sure your IP is whitelisted so it can connect to mongodb [here](https://cloud.mongodb.com/v2/5e749804009db21dd6c90af1#security/network/accessList)

**Comment by DiabolicAngeL** [comment]
Both checked. I have allowed access to all and I added the server ip too just in case..
![image](https://user-images.githubusercontent.com/68332732/104348664-a8811d80-550a-11eb-99f3-88fc964df438.png)
![image](https://user-images.githubusercontent.com/68332732/104348676-adde6800-550a-11eb-8971-b94eca5c19f5.png)

**Comment by tovade** [comment]
did u fill in the pass?

**Comment by DiabolicAngeL** [comment]
> did u fill in the pass?

yeap

Ps. When I create a database I put the database name, what should I put in collection name? Maybe that's what i'm doing wrong? I don't know

**Comment by DiabolicAngeL** [comment]
Problem solved.
If anyone else have the same problem, be sure to open the following ports.

`27015,27016,27017`

https://docs.atlas.mongodb.com/troubleshoot-connection#attempting-to-connect-to-a-cluster-from-behind-a-firewall
