### ISSUE TITLE
Dashboard not working!

### ISSUE THREAD

**Issue by biswajitguha01** [casperiv0/ghostybot#161]
I was host it on local PC & dashboard url is http://localhost:3030, it open website properly but not open dashboard, I put jwt secret key perfectly & callback url perfectly but not open dashboard.

**Comment by casperiv0** [comment]
can you provide more info than just "not open dashboard".

**Comment by biswajitguha01** [comment]
https://user-images.githubusercontent.com/75612666/104475054-a8ede700-55e4-11eb-9be0-f932a71acfc0.mov

**Comment by biswajitguha01** [comment]
This is the problem

**Comment by casperiv0** [comment]
ah, sorry. That's an issue I don't know where it comes from or why it occurs.
