### ISSUE TITLE
Mongoose Error

### ISSUE THREAD

**Issue by RedHexDiscord** [casperiv0/ghostybot#162]
**Description**
Error with the DB, however, the URI is all good :/
![image](https://user-images.githubusercontent.com/63918506/104638654-7be91500-5674-11eb-92c7-fd7e099f8e56.png)

**Comment by RedHexDiscord** [comment]
I think this might actually be a bug, :/. Also, how would you do the callbackUrl

**Comment by casperiv0** [comment]
It's not a bug. Make sure you have installed everything correctly.
