### ISSUE TITLE
Hactoberfest Participate Request

### ISSUE THREAD

**Issue by LackyPal** [casperiv0/ghostybot#35]
Why don't you participate in hactoberfest ? It's great to do that. Please add this repo on hactoberfest. 🙏
By doing this, i think more people will come to contribute.

**Comment by Tegnio** [comment]
👍🏻

**Comment by tovade** [comment]
Hmm idk but its caspers choice also people from hacktoberfest are smart and dont use quick.db anymore i think but like i hope it does no hate do

**Comment by casperiv0** [comment]
Ill think about it when im home later today.

**Comment by casperiv0** [comment]
I've decided to go with it, feel free to open pull requests and let me know if it's for hacktoberfest so I can add the labels. 

**Read**

1. Do NOT violate the rules of hacktoberfest
2. Do NOT spam this repo with poor pull requests

**Comment by LackyPal** [comment]
Thanks for it. 🥰
