### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by LackyPal** [casperiv0/ghostybot#44]
**Describe the bug**
There is a spelling mistake at line [#36](https://github.com/Dev-CasperTheGhost/ghostybot/blob/a8e9e072e79386c12754c29c3909c41b31997846/src/events/guildMemberRemove.js#L36)
**Command**
          `**${user.usernme}#${user.discriminator}** just left us.`,

**To Reproduce**
1. Go to 'https://github.com/Dev-CasperTheGhost/ghostybot/blob/a8e9e072e79386c12754c29c3909c41b31997846/src/events/guildMemberRemove.js#L36'
2. Rename ``${user.usernme}`` to ``${user.username}``

**Expected behavior**
It should be ``${user.username}``

**Screenshots**
https://cdn.discordapp.com/attachments/704954812369731604/764152301388169246/IMG_20201009_211812.jpg

**Comment by casperiv0** [comment]
Thanks for reporting this bug! This issue should be fixed.

**Comment by LackyPal** [comment]
Yea, actually it's my mistake. I forget to check correctly before submitting the pull request #36 .

**Comment by casperiv0** [comment]
No worries haha.
