### ISSUE TITLE
error while starting

### ISSUE THREAD

**Issue by Debelox** [casperiv0/ghostybot#87]
**Description**
Please provide as much info as you can.

There is a big error in console while starting the bot , something related to sqlite.

**Comment by casperiv0** [comment]
Can you please provide more info. By saying 'a big error in console while starting bot' is not very helpful. Please include screenshots if you can too.

**Comment by LackyPal** [comment]
Please explain your ``error`` in details. Better you join the Support Server.(Link in Readme)

**Comment by casperiv0** [comment]
Closed due to inactivity & no response.
